// Alphabet Position letter shortest path
// TERNARY OPERATOR
// IF ELSE
// SWICH CASE 
// FOR LOOP
// RETURN 
// to work on the website


// PHYTON WERSION      Alphabet Position letter shortest path

// def position(letter):
//     Letter = 'abcdefghijklmnopqrstuvwxyz'
//     count = 0
//     for i in Letter:
//         if i == letter:
//             return f'Position of Letter: {count + 1}'
//         count += 1
//     return 'Invalid letter'


// letter = input("Enter a letter: ").lower()
// print(position(letter))


// TERNARY OPERATOR

function position(letter) {
    const letters = 'abcdefghijklmnopqrstuvwxyz'
    let caunt = 0
    for (let i of letters) {
        if (i === letter){
            return 
        }
    }
}